// This file is generated by the generate-abis script. Do not modify it manually.

import { RewardRatePoolAbi } from './RewardRatePool';
import { SENTAbi } from './SENT';
import { ServiceNodeContributionAbi } from './ServiceNodeContribution';
import { ServiceNodeContributionFactoryAbi } from './ServiceNodeContributionFactory';
import { ServiceNodeRewardsAbi } from './ServiceNodeRewards';
import { BN256G1Abi } from './BN256G1';
import { BN256G2Abi } from './BN256G2';
import { PairingAbi } from './Pairing';
import { SharedAbi } from './Shared';
import { TokenConverterAbi } from './TokenConverter';
import { TokenVestingNoStakingAbi } from './TokenVestingNoStaking';
import { TokenVestingStakingAbi } from './TokenVestingStaking';
import { TestnetServiceNodeRewardsAbi } from './TestnetServiceNodeRewards';

export const Contracts = {
  RewardRatePool: RewardRatePoolAbi,
  SENT: SENTAbi,
  ServiceNodeContribution: ServiceNodeContributionAbi,
  ServiceNodeContributionFactory: ServiceNodeContributionFactoryAbi,
  ServiceNodeRewards: ServiceNodeRewardsAbi,
  TestnetServiceNodeRewards: TestnetServiceNodeRewardsAbi,
  BN256G1: BN256G1Abi,
  BN256G2: BN256G2Abi,
  Pairing: PairingAbi,
  Shared: SharedAbi,
  TokenConverter: TokenConverterAbi,
  TokenVestingNoStaking: TokenVestingNoStakingAbi,
  TokenVestingStaking: TokenVestingStakingAbi,
} as const;
export type ContractWithAbiName = keyof typeof Contracts;
export type ContractAbis = typeof Contracts;
export {
  RewardRatePoolAbi,
  SENTAbi,
  ServiceNodeContributionAbi,
  ServiceNodeContributionFactoryAbi,
  ServiceNodeRewardsAbi,
  BN256G1Abi,
  BN256G2Abi,
  PairingAbi,
  SharedAbi,
  TokenConverterAbi,
  TokenVestingNoStakingAbi,
  TokenVestingStakingAbi,
  TestnetServiceNodeRewardsAbi,
};
